-- SQL Schema for Roalux MixLab
-- Run this in the Supabase SQL Editor (https://app.supabase.com/project/_/sql)

-- 1. Create 'items' table
CREATE TABLE IF NOT EXISTS public.items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT,
    name TEXT NOT NULL,
    unit TEXT NOT NULL,
    price NUMERIC DEFAULT 0,
    cat TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create 'products' table
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    batch NUMERIC DEFAULT 0,
    "desc" TEXT,
    density NUMERIC DEFAULT 0, -- kg per litre
    group_code TEXT, -- 3 character code (e.g. REX, ABC)
    color TEXT, -- Product color name
    stages TEXT, -- Stores JSON string
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Create 'stocks' table
CREATE TABLE IF NOT EXISTS public.stocks (
    "itemId" BIGINT PRIMARY KEY REFERENCES public.items(id) ON DELETE CASCADE,
    qty NUMERIC DEFAULT 0,
    "avgPrice" NUMERIC DEFAULT 0,
    threshold NUMERIC DEFAULT 0
);

-- 4. Create 'production_history' table
CREATE TABLE IF NOT EXISTS public.production_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES public.products(id) ON DELETE SET NULL,
    product_name TEXT NOT NULL,
    quantity NUMERIC NOT NULL,
    batch_number TEXT NOT NULL,
    stages_data TEXT, -- Stores JSON string of the scaled formulation
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS) if needed, or just allow all for now
ALTER TABLE public.items DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.products DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.stocks DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.production_history DISABLE ROW LEVEL SECURITY;

-- 5. Create 'stock_batches' table for FIFO costing
CREATE TABLE IF NOT EXISTS public.stock_batches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "itemId" BIGINT REFERENCES public.items(id) ON DELETE CASCADE,
    qty NUMERIC NOT NULL, -- Remaining qty in this batch
    price NUMERIC NOT NULL, -- Purchase price per unit
    vendor TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.stock_batches DISABLE ROW LEVEL SECURITY;

-- 6. FIFO Deduction Function (Run this in Supabase SQL Editor)
-- This function deducts stock from batches in FIFO order and returns the total cost.
/*
CREATE OR REPLACE FUNCTION consume_stock_fifo(p_item_id BIGINT, p_qty_to_deduct NUMERIC)
RETURNS NUMERIC AS $$
DECLARE
    v_remaining_qty NUMERIC := p_qty_to_deduct;
    v_batch_qty NUMERIC;
    v_batch_id BIGINT;
    v_batch_price NUMERIC;
    v_total_cost NUMERIC := 0;
    v_deduct_qty NUMERIC;
BEGIN
    FOR v_batch_id, v_batch_qty, v_batch_price IN 
        SELECT id, qty, price FROM public.stock_batches 
        WHERE "itemId" = p_item_id AND qty > 0 
        ORDER BY created_at ASC
    LOOP
        IF v_remaining_qty <= 0 THEN
            EXIT;
        END IF;

        v_deduct_qty := LEAST(v_remaining_qty, v_batch_qty);
        v_total_cost := v_total_cost + (v_deduct_qty * v_batch_price);
        
        UPDATE public.stock_batches 
        SET qty = qty - v_deduct_qty 
        WHERE id = v_batch_id;

        v_remaining_qty := v_remaining_qty - v_deduct_qty;
    END LOOP;

    -- Update summary stocks table
    UPDATE public.stocks 
    SET qty = qty - p_qty_to_deduct 
    WHERE "itemId" = p_item_id;

    RETURN v_total_cost;
END;
$$ LANGUAGE plpgsql;
*/

-- 7. Refresh PostgREST schema cache
NOTIFY pgrst, 'reload schema';
